using Serenity.Navigation;
using MyPages = EMR.Configs.Pages;
//using Serenity.Navigation;
//using MyPages = EMR.Configs.Pages;

//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Diseases Category", typeof(MyPages.TblDiseasesCategoryController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Education", typeof(MyPages.TblEducationController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Examinations Details", typeof(MyPages.TblExaminationsDetailsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Marital Status", typeof(MyPages.TblMaritalStatusController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Occupation", typeof(MyPages.TblOccupationController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Outcomes Mother", typeof(MyPages.TblOutcomesMotherController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Positions", typeof(MyPages.TblPositionsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Professions", typeof(MyPages.TblProfessionsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Relation", typeof(MyPages.TblRelationController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Ward", typeof(MyPages.TblWardController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Ward Diseases", typeof(MyPages.TblWardDiseasesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Blood Group", typeof(MyPages.TblBloodGroupController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Gender", typeof(MyPages.TblGenderController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Hf Health Facilities", typeof(MyPages.HfHealthFacilitiesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Wrd Var", typeof(MyPages.TblWrdVarController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Age Types", typeof(MyPages.TblAgeTypesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Case Types", typeof(MyPages.TblCaseTypesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Child", typeof(MyPages.TblChildController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Nb Result", typeof(MyPages.TblNbResultController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Nbstatus", typeof(MyPages.TblNbstatusController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Nb Weight", typeof(MyPages.TblNbWeightController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Diagnosis", typeof(MyPages.TblDiagnosisController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Tbl Abortion Type", typeof(MyPages.TblAbortionTypeController), icon: null)]
////[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Patient Type", typeof(MyPages.LkpPatientTypeController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Manufacturer", typeof(MyPages.LkpManufacturerController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Unit", typeof(MyPages.LkpUnitController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Vendor", typeof(MyPages.LkpVendorController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Form", typeof(MyPages.LkpFormController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp History", typeof(MyPages.LkpHistoryController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Lab Test", typeof(MyPages.LkpLabTestController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Phys Exams", typeof(MyPages.LkpPhysExamsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Phys Group", typeof(MyPages.LkpPhysGroupController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Imaging", typeof(MyPages.LkpImagingController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Typeofvisit", typeof(MyPages.TypeofvisitController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Ethnicity", typeof(MyPages.EthnicityController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Recommands", typeof(MyPages.LkpRecommandsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Test Types", typeof(MyPages.LkpTestTypesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Phys Exam Group", typeof(MyPages.LkpPhysExamGroupController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Countries", typeof(MyPages.CountriesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Topography Main", typeof(MyPages.TopographyMainController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Topography Sub", typeof(MyPages.TopographySubController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Lkp Losstypes", typeof(MyPages.LkpLosstypesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Caretypes", typeof(MyPages.CaretypesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Configs/Cycles", typeof(MyPages.CyclesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Configs/Stages", typeof(MyPages.StagesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Configs/Blood Status", typeof(MyPages.BloodStatusController), icon: null)]